version: '2'
services:
  php-apache2:
    image: cikupin/php-apache2:5.6-1
    container_name: php-apache2-5.6
    volumes:
      - ./etc/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - /var/www/html:/var/www/html # htdocs mounting point
    ports:
      - 80:80
    networks:
      - net-lampp-5.6

  mariadb-docker:
    image: mariadb:10.3.0
    container_name: mariadb-docker-10.3
    environment:
       - MYSQL_ROOT_PASSWORD=my-secret-pw
       - MYSQL_ROOT_HOST=%
    volumes:
      - ~/Apps/docker_data/mariadb:/var/lib/mysql # mysql data mounting point
    ports:
      - 3306:3306
    networks:
      - net-lampp-5.6

  redis-docker:
    image: redis:3.0.7-alpine
    container_name: redis-3.0.7-alpine
    ports:
      - 6379:6379
    networks:
      - net-lampp-5.6

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin-4.8
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mariadb-docker
     - PMA_PORTS=3306
     - PMA_USER=root
     - PMA_PASSWORD=my-secret-pw
    restart: always
    ports:
     - 8080:80
    networks:
      - net-lampp-5.6

  rabbitmq-docker:
    image: rabbitmq:3.6.10-management-alpine
    container_name: rabbitmq-3.6.10
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672

    networks:
      - net-lampp-5.6

  beanstalkd-docker:
    image: cikupin/beanstalkd:1.10-alpine
    container_name: beanstalkd-1.10
    ports:
      - 11300:11300
    networks:
      - net-lampp-5.6

  mongodb-docker:
    image: cikupin/mongodb-alpine:3.4.4
    container_name: mongodb-3.4.4
    volumes:
      - ~/Apps/docker_data/mongodb:/data/db #mongodb data mounting point
    ports:
      - 27017:27017
    networks:
      - net-lampp-5.6

networks:
  net-lampp-5.6:
    driver: "bridge"
